### ISSUE TITLE
Run game in headless mode

### ISSUE THREAD

**Issue by jdno** [jdno/auto-traffic-control#290]
## Overview

The [next version of the game](https://github.com/jdno/auto-traffic-control/milestone/1) implements a new architecture for the game, which makes it possible to run the simulation in a _headless_ mode without rendering a user interface. Besides being a [requested feature](https://github.com/jdno/auto-traffic-control/discussions/171), this functionality also enables us to test the new architecture before building the user interface.

### Design

We will add a command-line tool to the project that players can use to launch the game.

```shell
cargo run -p cli
```

In [version 0.4](https://github.com/jdno/auto-traffic-control/milestone/1), the CLI will only run the simulation. Later versions might add more features, at which point we will redesign the commands and arguments of the CLI.

## Features

- [x] Create a new crate for the command-line tool
- [x] Launch the simulation and run its game loop
- [x] Package the CLI as a Docker image
